name: note_app
description: Note App.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # F
  flutter_staggered_grid_view: ^0.4.0
  flutter_launcher_icons: ^0.9.2
  
  # S
  splashscreen: ^1.3.5
  sqflite: ^2.0.0+4

  # U
  uuid: ^3.0.4
  package_info: ^2.0.2
  popover: ^0.2.6+2
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "?"

flutter:

  uses-material-design: true

  assets:
  - assets/images/